"""Add pooled historical cash correction

Revision ID: 4da8924fa6ad
Revises: e1bcab423d37
Create Date: 2026-09-15 22:16:37.501931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da8924fa6ad'
down_revision = 'e1bcab423d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.Enum('ISSUED', 'RETURN', name='cash_movement_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'VOID', name='cash_movement_status'), nullable=False),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_cash_movement_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_cash_movements_movement_date'), ['movement_date'], unique=False)

    with op.batch_alter_table('historical_official_monthly_totals', schema=None) as batch_op:
        # server_default backfills existing rows (production already has
        # locked Jan-Sep 2026 rows) with 0 before the NOT NULL applies.
        batch_op.add_column(sa.Column('historical_issued_allocated', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('historical_official_monthly_totals', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_historical_issued_allocated_nonneg', 'historical_issued_allocated >= 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_official_monthly_totals', schema=None) as batch_op:
        batch_op.drop_constraint('ck_historical_issued_allocated_nonneg', type_='check')

    with op.batch_alter_table('historical_official_monthly_totals', schema=None) as batch_op:
        batch_op.drop_column('historical_issued_allocated')

    with op.batch_alter_table('historical_cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_cash_movements_movement_date'))

    op.drop_table('historical_cash_movements')
    # ### end Alembic commands ###

    # Autogenerate does not reverse-drop the Postgres ENUM types it
    # created for historical_cash_movements' columns - clean them up so
    # a downgrade truly reverses the upgrade.
    sa.Enum(name='cash_movement_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cash_movement_status').drop(op.get_bind(), checkfirst=True)
