"""Initial schema

Revision ID: e1bcab423d37
Revises: 
Create Date: 2026-09-14 17:22:33.010737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bcab423d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('fund_type', sa.Enum('MUKULULO', 'FRIDAY_SUNDAY', name='bank_account_fund_type'), nullable=False),
    sa.Column('opening_balance', sa.Integer(), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DATA_ENTRY', 'COLLECTOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'EDIT', 'VOID', 'LOCK', 'UNLOCK', 'LOGIN', 'LOGIN_FAILED', 'DEACTIVATE', 'ACTIVATE', 'RESET_PASSWORD', 'MERGE', 'OVERRIDE', name='audit_action'), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('bank_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INCREASE', 'DECREASE', name='adjustment_direction'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_adjustment_amount_positive'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('fund', sa.Enum('MUKULULO', 'FRIDAY_SUNDAY', name='deposit_fund_type'), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('slip_reference', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('exceeds_available', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_deposit_amount_positive'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_deposits_deposit_date'), ['deposit_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_deposits_fund'), ['fund'], unique=False)

    op.create_table('bank_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('actual_balance', sa.Integer(), nullable=False),
    sa.Column('estimated_balance_snapshot', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECONCILED', 'DIFFERENCE', name='reconciliation_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mukululo_system_total', sa.Integer(), nullable=False),
    sa.Column('friday_system_total', sa.Integer(), nullable=False),
    sa.Column('sunday_system_total', sa.Integer(), nullable=False),
    sa.Column('physical_cash_counted', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('BALANCED', 'SHORT', 'OVER', name='session_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_sessions_date'), ['date'], unique=True)

    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_normalized', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['contributors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized', name='uq_contributor_name_normalized')
    )
    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.create_index('ix_contributors_active', ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributors_name_normalized'), ['name_normalized'], unique=False)

    op.create_table('historical_official_monthly_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('mukululo_total', sa.Integer(), nullable=False),
    sa.Column('friday_total', sa.Integer(), nullable=False),
    sa.Column('sunday_total', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_historical_month_range'),
    sa.CheckConstraint('mukululo_total >= 0 AND friday_total >= 0 AND sunday_total >= 0', name='ck_historical_totals_nonneg'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_historical_total_year_month')
    )
    op.create_table('contribution_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('collection_type', sa.Enum('MUKULULO', 'FRIDAY', 'SUNDAY', name='collection_type'), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_historical_backentry', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'VOID', name='transaction_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribution_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_transactions_collection_type'), ['collection_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_transactions_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_transactions_date'), ['date'], unique=False)
        batch_op.create_index('ix_transactions_date_type', ['date', 'collection_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_date_type')
        batch_op.drop_index(batch_op.f('ix_contribution_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_contribution_transactions_contributor_id'))
        batch_op.drop_index(batch_op.f('ix_contribution_transactions_collection_type'))

    op.drop_table('contribution_transactions')
    op.drop_table('historical_official_monthly_totals')
    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributors_name_normalized'))
        batch_op.drop_index('ix_contributors_active')

    op.drop_table('contributors')
    with op.batch_alter_table('collection_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_sessions_date'))

    op.drop_table('collection_sessions')
    op.drop_table('bank_reconciliations')
    with op.batch_alter_table('bank_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_deposits_fund'))
        batch_op.drop_index(batch_op.f('ix_bank_deposits_deposit_date'))

    op.drop_table('bank_deposits')
    op.drop_table('bank_adjustments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))

    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
